---
services:
  gate-b:
    container_name: gate-b
    image: ghcr.io/minekube/gate:latest
    restart: unless-stopped
    volumes:
      - ./config.yml:/config.yml
    networks:
      - default
      - gate

networks:
  default:
    name: gate-b
  gate:
    external: true
